<?php
$product_id = !empty($wo['product']['id']) ? (int) $wo['product']['id'] : 0;
$product_url = !empty($wo['product']['url']) ? $wo['product']['url'] : 'javascript:void(0)';
$product_seo_id = !empty($wo['product']['seo_id']) ? $wo['product']['seo_id'] : $product_id;
$product_name = !empty($wo['product']['name']) ? $wo['product']['name'] : '';
$product_image = !empty($wo['product']['images'][0]['image_org']) ? $wo['product']['images'][0]['image_org'] : '';
$product_price_display = !empty($wo['product']['price_display']) ? $wo['product']['price_display'] : '';
?>
<div class="wo_my_products col-xs-6 col-sm-4 col-md-3" id="product_<?php echo $product_id;?>">
	<a href="<?php echo $product_url;?>" data-ajax="?link1=post&id=<?php echo $product_seo_id;?>">
      <div class="avatar">
         <img src="<?php echo $product_image;?>" alt="<?php echo $product_name; ?> Profile Picture" />
      </div>
      <div class="produc_info">
		 <span title="<?php echo $product_name; ?>"><?php echo $product_name; ?></span>
		 <h4><?php echo $product_price_display; ?></h4>
      </div>
	</a>
   <?php if ($wo['loggedin'] && !empty($wo['product']['user_id']) && $wo['product']['user_id'] == $wo['user']['user_id']) { ?>
      <span onclick="RemoveUserProduct(<?php echo $product_id;?>,'hide')" class="pointer product-list"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather"><path fill="currentColor" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z"></path></svg></span>
   <?php } ?>
</div>
